# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [2]:
### [your code here]
print("NumPy version:")
print(np.__version__)

print("\nNumPy configuration:")
np.show_config()


NumPy version:
2.3.5

NumPy configuration:
Build Dependencies:
  blas:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/SuzanaSouza/anaconda3/Library/include
    lib directory: C:/Users/SuzanaSouza/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
  lapack:
    detection method: pkgconfig
    found: true
    include directory: C:/Users/SuzanaSouza/anaconda3/Library/include
    lib directory: C:/Users/SuzanaSouza/anaconda3/Library/lib
    name: mkl-sdl
    openblas configuration: unknown
    pc file directory: C:\miniconda3\conda-bld\numpy_and_numpy_base_1763980694785\_h_env\Library\lib\pkgconfig
    version: '2025'
Compilers:
  c:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  c++:
    commands: cl.exe
    linker: link
    name: msvc
    version: 19.29.30159
  cython:


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [3]:
### [your code here]
a = np.random.randint(1,10, size=(2, 3, 5))#In this formula first is the blocks, after the row and last the column


### 4. Print a.


In [4]:
### [your code here]
print(a)

[[[3 8 1 7 3]
  [4 7 3 5 1]
  [7 8 3 4 5]]

 [[3 8 2 5 6]
  [8 3 7 7 7]
  [5 6 2 4 6]]]


In [5]:
a = np.random.rand(2, 3, 5)#Generates random floats in the range [0, 1]
print(a)

[[[0.38656496 0.83495877 0.55708689 0.13224153 0.1001957 ]
  [0.42399477 0.71009641 0.14511358 0.61729859 0.17889298]
  [0.19576764 0.11348914 0.54916435 0.00095623 0.53793537]]

 [[0.03290764 0.52276756 0.31982326 0.76005227 0.36947251]
  [0.77511814 0.11858878 0.00972058 0.32365377 0.05286843]
  [0.22515642 0.41563777 0.20886807 0.75688084 0.72602587]]]


In [6]:
a = np.random.random((2, 3, 5))# shape as a tuple 
print(a)

[[[0.27832057 0.99958247 0.19092448 0.81109366 0.5140454 ]
  [0.47155102 0.54873524 0.37636772 0.23166927 0.20988708]
  [0.01865514 0.32723631 0.34157225 0.70317181 0.78837055]]

 [[0.17325981 0.55439525 0.87158335 0.57145744 0.18718134]
  [0.04895251 0.51162496 0.83769312 0.59770103 0.2483696 ]
  [0.64075796 0.46206072 0.05105568 0.3870058  0.01945571]]]


In [7]:
a = np.random.uniform(0, 1, (2, 3, 5))#specify the range of random values
print(a)

[[[0.9688195  0.06218113 0.54615654 0.81963212 0.2222579 ]
  [0.50358852 0.42311184 0.46780416 0.57036474 0.708717  ]
  [0.85288398 0.93595321 0.17125102 0.1296978  0.53902564]]

 [[0.5353657  0.30544889 0.17033137 0.76489485 0.72718004]
  [0.23881397 0.78946399 0.48430439 0.36889143 0.404874  ]
  [0.12411113 0.20275287 0.52326789 0.23750919 0.55041125]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [8]:
### [your code here]
b = np.ones((5, 2, 3))



### 6. Print b.


In [9]:
### [your code here]
print (b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [10]:
b = np.full((5, 2, 3), 1)
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


In [11]:
b = np.zeros((5, 2, 3)) + 1
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [12]:
### [your code here]
print(a.size)
print(b.size)

print(a.size == b.size)

30
30
True



### 8. Are you able to add a and b? Why or why not?


In [13]:
### [your code here]

#No, you cannot directly add a and b because NumPy requires compatible shapes to perform element-wise addition, and a and b have different shapes

print(a.shape)
print(b.shape)
a.shape == b.shape

(2, 3, 5)
(5, 2, 3)


False



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [14]:
### [your code here]
# To make b match the structure of a, we need to reorder the axes
c = np.transpose(b, (1, 2, 0))
print(c.shape)

(2, 3, 5)


In [15]:
#also this sintex - same result
c = b.transpose(1, 2, 0)
print(c.shape)

(2, 3, 5)


In [16]:
print(a.shape)
print(b.shape)
print(c.shape)

(2, 3, 5)
(5, 2, 3)
(2, 3, 5)


In [17]:
# a and b dont have same shape
#NumPy follows this rule:
## - Operations do not modify arrays unless you explicitly ask for it to prevents accidental data corruption and hard-to-debug side effects
## - To really change b, must reassign it
b = np.transpose(b, (1, 2, 0))
print(b.shape)

(2, 3, 5)


In [18]:
print(a.shape)
print(b.shape)
print(c.shape)

(2, 3, 5)
(2, 3, 5)
(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [19]:
### [your code here]
d = a + c
print(d)
print(d.shape)

# before, addition of a and b failed because was the arrays was not on same shape 
# now a and c arrays has the same shape

[[[1.9688195  1.06218113 1.54615654 1.81963212 1.2222579 ]
  [1.50358852 1.42311184 1.46780416 1.57036474 1.708717  ]
  [1.85288398 1.93595321 1.17125102 1.1296978  1.53902564]]

 [[1.5353657  1.30544889 1.17033137 1.76489485 1.72718004]
  [1.23881397 1.78946399 1.48430439 1.36889143 1.404874  ]
  [1.12411113 1.20275287 1.52326789 1.23750919 1.55041125]]]
(2, 3, 5)



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [20]:
### [your code here]
print("Array a:")
print(a)

print("\nArray d = a + c:")
print(d)



Array a:
[[[0.9688195  0.06218113 0.54615654 0.81963212 0.2222579 ]
  [0.50358852 0.42311184 0.46780416 0.57036474 0.708717  ]
  [0.85288398 0.93595321 0.17125102 0.1296978  0.53902564]]

 [[0.5353657  0.30544889 0.17033137 0.76489485 0.72718004]
  [0.23881397 0.78946399 0.48430439 0.36889143 0.404874  ]
  [0.12411113 0.20275287 0.52326789 0.23750919 0.55041125]]]

Array d = a + c:
[[[1.9688195  1.06218113 1.54615654 1.81963212 1.2222579 ]
  [1.50358852 1.42311184 1.46780416 1.57036474 1.708717  ]
  [1.85288398 1.93595321 1.17125102 1.1296978  1.53902564]]

 [[1.5353657  1.30544889 1.17033137 1.76489485 1.72718004]
  [1.23881397 1.78946399 1.48430439 1.36889143 1.404874  ]
  [1.12411113 1.20275287 1.52326789 1.23750919 1.55041125]]]


In [21]:
# a contains random values between 0 and 1 (from when we generated it).

# c contains all ones (it’s the transposed version of b which was filled with ones).

# d = a + c adds 1 to every element of a.

#a[0,0,:] = [0.3, 0.7, 0.2, 0.9, 0.5]
#c[0,0,:] = [1, 1, 1, 1, 1]
#d[0,0,:] = a[0,0,:] + c[0,0,:] = [1.3, 1.7, 1.2, 1.9, 1.5]

#d[i,j,k]=a[i,j,k]+1


### 12. Multiply a and c. Assign the result to e.


In [22]:
### [your code here]
e = a * c
print(e)
print(e.shape)


[[[0.9688195  0.06218113 0.54615654 0.81963212 0.2222579 ]
  [0.50358852 0.42311184 0.46780416 0.57036474 0.708717  ]
  [0.85288398 0.93595321 0.17125102 0.1296978  0.53902564]]

 [[0.5353657  0.30544889 0.17033137 0.76489485 0.72718004]
  [0.23881397 0.78946399 0.48430439 0.36889143 0.404874  ]
  [0.12411113 0.20275287 0.52326789 0.23750919 0.55041125]]]
(2, 3, 5)




### 13. Does e equal to a? Why or why not?


In [23]:
### [your code here]
#YES, e==a
print(np.all(e == a))   # True if all elements are equal


True


In [24]:
#other simple way to check if they e ==a
print(e.shape == a.shape)

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [25]:
### [your code here]

#USING FUNCTION FOR MAX - array is a argument and works on any array-like object (lists,tuples,NumPy arrays)
d_max = np.max(d)
print("Maximum value in d:", d_max)


Maximum value in d: 1.9688195049517696


In [26]:
# USING ARRAY METHOD
d_max = d.max()#only works on Numpy arrays
print("Maximum value in d:", d_max)

Maximum value in d: 1.9688195049517696


In [27]:
#USING FUNCTION FOR MIN
d_min = np.min(d)
print("Minimum value in d:", d_min)

Minimum value in d: 1.0621811259828133


In [28]:
#USING ARRAY METHOD FOR MIN
d_min = d.min()
print("Minimum value in d:", d_min)

Minimum value in d: 1.0621811259828133


In [29]:
#USING FUNCTION FOR MEAN
d_mean = np.mean(d)
print("Mean value in d:", d_mean)

Mean value in d: 1.4783022017815992


In [30]:
#USING ARRAY METHOD FOR MEAN
d_mean = d.mean()
print("Mean value in d:", d_mean)

Mean value in d: 1.4783022017815992



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [31]:
### [your code here]
f = np.empty(d.shape)
print(f)
print("Shape of f:", f.shape)

[[[0.9688195  0.06218113 0.54615654 0.81963212 0.2222579 ]
  [0.50358852 0.42311184 0.46780416 0.57036474 0.708717  ]
  [0.85288398 0.93595321 0.17125102 0.1296978  0.53902564]]

 [[0.5353657  0.30544889 0.17033137 0.76489485 0.72718004]
  [0.23881397 0.78946399 0.48430439 0.36889143 0.404874  ]
  [0.12411113 0.20275287 0.52326789 0.23750919 0.55041125]]]
Shape of f: (2, 3, 5)


In [32]:
#LABELING THE ELEMENTS
#label the elements of d in f based on standard thresholds

# Assume d_mean is already calculated
# f is the empty array we created

# Loop over all elements (because we want to avoid fancy functions)
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] < d_mean:
                f[i, j, k] = 0
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 1
            else:  # d[i, j, k] > d_mean
                f[i, j, k] = 2

print("Labeled array f:")
print(f)

#Explanation:
#f has the same shape as d → (2, 3, 5)
#Each element in d is compared to d_mean
#Labels are assigned based on the value:
# < mean → 0
# == mean → 1
# > mean → 2

Labeled array f:
[[[2. 0. 2. 2. 0.]
  [2. 0. 0. 2. 2.]
  [2. 2. 0. 0. 2.]]

 [[2. 0. 0. 2. 2.]
  [0. 2. 2. 0. 0.]
  [0. 0. 2. 0. 2.]]]


In [33]:
# OTHER WAY TO LABEL 
# Assume d and d_mean are already defined
f = np.empty(d.shape)

# Create labels using boolean masks
f[d < d_mean] = 0
f[d == d_mean] = 1
f[d > d_mean] = 2

print("Labeled array f (vectorized):")
print(f)

#Explanation
#d < d_mean → returns a boolean array where each element is True if it’s less than the mean.
#f[d < d_mean] = 0 → assigns 0 to all those positions.
#d == d_mean → assigns 1 to elements equal to the mean.
#d > d_mean → assigns 2 to elements greater than the mean.

Labeled array f (vectorized):
[[[2. 0. 2. 2. 0.]
  [2. 0. 0. 2. 2.]
  [2. 2. 0. 0. 2.]]

 [[2. 0. 0. 2. 2.]
  [0. 2. 2. 0. 0.]
  [0. 0. 2. 0. 2.]]]





### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [34]:
### [your code here]
# Assume d is already defined

# Calculate statistics
d_min = d.min()
d_max = d.max()
d_mean = d.mean()

# Create empty array with same shape as d
f = np.empty(d.shape)

# Populate f based on rules
f[d == d_min] = 0               # d_min -> 0
f[(d > d_min) & (d < d_mean)] = 25  # d_min < d < d_mean -> 25
f[d == d_mean] = 50             # d == d_mean -> 50
f[(d > d_mean) & (d < d_max)] = 75  # d_mean < d < d_max -> 75
f[d == d_max] = 100             # d_max -> 100

# Verify f contains only the allowed values
print("Unique values in f:", np.unique(f))

# Print results
print("\nArray d:\n", d)
print("\nLabeled array f:\n", f)


Unique values in f: [  0.  25.  75. 100.]

Array d:
 [[[1.9688195  1.06218113 1.54615654 1.81963212 1.2222579 ]
  [1.50358852 1.42311184 1.46780416 1.57036474 1.708717  ]
  [1.85288398 1.93595321 1.17125102 1.1296978  1.53902564]]

 [[1.5353657  1.30544889 1.17033137 1.76489485 1.72718004]
  [1.23881397 1.78946399 1.48430439 1.36889143 1.404874  ]
  [1.12411113 1.20275287 1.52326789 1.23750919 1.55041125]]]

Labeled array f:
 [[[100.   0.  75.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  75.]]

 [[ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  25.  75.]]]






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [36]:
### [your code here]
print("Expected d:", d)

Expected d: [[[1.9688195  1.06218113 1.54615654 1.81963212 1.2222579 ]
  [1.50358852 1.42311184 1.46780416 1.57036474 1.708717  ]
  [1.85288398 1.93595321 1.17125102 1.1296978  1.53902564]]

 [[1.5353657  1.30544889 1.17033137 1.76489485 1.72718004]
  [1.23881397 1.78946399 1.48430439 1.36889143 1.404874  ]
  [1.12411113 1.20275287 1.52326789 1.23750919 1.55041125]]]


In [38]:
print("Expected f:", f)

Expected f: [[[100.   0.  75.  75.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  75.]]

 [[ 75.  25.  25.  75.  75.]
  [ 25.  75.  75.  25.  25.]
  [ 25.  25.  75.  25.  75.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [39]:
### [your code here]

# Original array d as a Python nested list
d = [
    [[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
     [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
     [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

    [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
     [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
     [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]
]

# Compute min, max, mean manually
flat = [x for plane in d for row in plane for x in row]  # flatten 3D list
d_min = min(flat)
d_max = max(flat)
d_mean = sum(flat)/len(flat)

# Create empty f with same shape
f = []

for plane in d:
    f_plane = []
    for row in plane:
        f_row = []
        for value in row:
            if value == d_min:
                f_row.append('A')
            elif d_min < value < d_mean:
                f_row.append('B')
            elif value == d_mean:
                f_row.append('C')
            elif d_mean < value < d_max:
                f_row.append('D')
            elif value == d_max:
                f_row.append('E')
        f_plane.append(f_row)
    f.append(f_plane)

# Print the labeled array
for plane in f:
    print(plane)


[['D', 'D', 'D', 'B', 'D'], ['D', 'D', 'B', 'B', 'B'], ['D', 'B', 'D', 'D', 'D']]
[['B', 'B', 'B', 'B', 'E'], ['D', 'D', 'D', 'D', 'D'], ['B', 'D', 'A', 'D', 'D']]
